### ISSUE TITLE
Station displays blank screen after logging in to Microsoft Teams

### ISSUE THREAD

**Issue by thelinuxcat** [getstation/desktop-app#80]
On MacOS Big Sir 11.6, sometime yesterday Station stopped working as expected.  When I login to Microsoft Teams, I get a blank screen where Teams used to be.

Station Version info:

![image](https://user-images.githubusercontent.com/93608904/140239274-a40e3525-3fcc-4de0-a08c-97962bf0dab6.png)

Blank Screen after logging into TEAMS.

![image](https://user-images.githubusercontent.com/93608904/140239250-6814fff9-556e-4232-a297-c7c9b693f99d.png)

I was using Station when Franz stopped working.   Now Station is not working.  

Let me know what other details are needed.

**Comment by rost100x** [comment]
Same, its was working at some point but then it stoped

**Comment by viktor44** [comment]
It works with Electron 24.2.0

**Comment by justinyotabyte** [comment]
I am also experiencing this issue

```0.1-app-prefetch.min-a1c1a7b.js:1 2023-09-20T05:34:57.428Z:CDLWorkerManager:undefined:"[CDLWorkerCacheManager]: Get from cache for key cdl-worker-startup-status could not find a result, returning null."
0.1-app-prefetch.min-a1c1a7b.js:1 2023-09-20T05:34:57.428Z:CDLWorkerManager:undefined:"[CDLWorkerCacheManager]: Saving item to cdl-worker-cache-manager key: cdl-worker-startup-status"
0.2-angular-jquery.min-14969ec.js:114 TypeError: Cannot read properties of undefined (reading 'once')
    at e.getElectronAppVersionInfo (https://statics.teams.cdn.office.net/hashed/3.2-app.min-8a72ebb.js:1:4126046)
    at yn.setIsPPTWPMinElectronVersionAvailable (https://statics.teams.cdn.office.net/hashed/3.1-app.min-d27d713.js:1:2051894)
    at n.yn (https://statics.teams.cdn.office.net/hashed/3.1-app.min-d27d713.js:1:95923)
    at new n (https://statics.teams.cdn.office.net/hashed/3.1-app.min-d27d713.js:1:14962739)
    at Object.instantiate (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:38:434)
    at Object.<anonymous> (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:39:226)
    at Object.invoke (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:38:333)
    at Object.$get (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:36:3)
    at Object.invoke (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:38:333)
    at https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:40:141 undefined```
